### PR TITLE
Bump dependencies

### PR DESCRIPTION
**Pull request by akegalj**
Bumps dependencies to purescript-0.10

### CODE REVIEW

**Comment by sectore** [comment]
@throughnothing Second commit ^ is needed to use `psc 0.11.x`.

**Comment by throughnothing** [comment]
Thanks!

**Comment by sectore** [comment]
@throughnothing Could you release  version `0.0.2` (commit 2353d08) and version `0.0.3` (commit e03425f), please? So that we have a versioning of `purescript-base58` (needed by `bower` and Co.). Thanks!

**Comment by throughnothing** [comment]
@sectore I just pushed 0.0.3, it looks like `pulp` had some extra requirements since I published the original (unversioned, it seems) version, which made it harder to cut a `0.0.2` publish.

**Pull request merged**
